/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {
	import avmplus.getQualifiedClassName;
	
	import flash.net.getClassByAlias;
	
	import mx.core.IUID;

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.AbstractEntity")]
    public class AbstractEntity extends AbstractEntityBase implements IUID {
		
		private var _uid:String = null;
		
		public function get uid():String
		{
			if (_uid == null)
				_uid = getQualifiedClassName(this) + ":" + id.toString();
			return _uid;
		}
		
		public function set uid(value:String):void
		{
		}
    }
}