/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {
	import flash.net.getClassByAlias;
	import flash.utils.getQualifiedClassName;
	
	import mx.core.FlexGlobals;
	import mx.core.IUID;
	import mx.rpc.AsyncToken;
	import mx.rpc.IResponder;

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.AbstractEntity")]
    public class AbstractEntity extends AbstractEntityBase implements IUID {
		
		private var _uid:String = null;
		
		public function get uid():String
		{
			if (_uid == null)
				_uid = getQualifiedClassName(this) + ":" + id.toString();
			return _uid;
		}
		
		public function set uid(value:String):void
		{
		}
		
		override public function deleteRecord(responder:IResponder=null):AsyncToken
		{
			return FlexGlobals.topLevelApplication.genericRE.remove(this);
		}
		
		override public function save(responder:IResponder=null):AsyncToken
		{
			return FlexGlobals.topLevelApplication.genericRE.save(this);
		}
   }
}