/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {
	import mx.resources.ResourceManager;

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.AbstractNamedEntity")]
	[ResourceBundle("messages")]
    public class AbstractNamedEntity extends AbstractNamedEntityBase {
		
		public function get label():String 
		{
			if (this.name == null && this.nameKey == null ) 
			{
				return "";
			}
			
			if (this.name == null || this.name.length == 0) {
				var resourceVal:String = ResourceManager.getInstance().getString("messages", this.nameKey);
				if (resourceVal == null || resourceVal.length == 0)
					return this.nameKey;
				else 
					return resourceVal;
			}
			else
				return this.name;
		}
    }
}