/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.ADDomainItem")]
    public class ADDomainItem extends ADDomainItemBase {
		
		public function get sortPriority(): Number
		{
			return 7;
		}
		
    }
}