/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {
	import mx.collections.ListCollectionView;
	import mx.collections.Sort;
	import mx.collections.SortField;

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.ADDomainItemGroup")]
    public class ADDomainItemGroup extends ADDomainItemGroupBase {
		
		protected var _isChildrenSorted:Boolean = false;
		
		override public function get children():ListCollectionView
		{
			if (_isChildrenSorted == false && super.children != null)
			{
				var sortLabel:Sort = new Sort();
				sortLabel.fields=[new SortField("sortPriority"), new SortField("label")];
				super.children.sort = sortLabel;
				super.children.refresh();
				_isChildrenSorted = true;
			}
			return super.children;
		}
		
		override public function set children(value:ListCollectionView):void
		{
			_isChildrenSorted = false;
			super.children = value;
		}
		
		override public function get sortPriority(): Number
		{
			return 3;
		}
    }
}