/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.ADDomainUser")]
    public class ADDomainUser extends ADDomainUserBase {
		
		[Embed("../../../../../../../../mydlp-ui-flex/src/main/flex/assets/icons/16x16/user.png")]
		public static const ICON_CLASS:Class;
		
		public function get icon(): Object
		{
			return ICON_CLASS;
		}
		
		public function get label(): String 
		{
			if (this.displayName != null && this.displayName.length > 0)
				return this.displayName;
			return this.sAMAccountName;
		}
		
		override public function get sortPriority(): Number
		{
			return 7;
		}
    }
}