/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.ADDomainOU")]
    public class ADDomainOU extends ADDomainOUBase {
		
		[Embed("../../../../../../../../mydlp-ui-flex/src/main/flex/assets/icons/16x16/users.png")]
		public static const ICON_CLASS:Class;
		
		public function get icon(): Object
		{
			return ICON_CLASS;
		}
		
		public function get label(): String
		{
			return this.name;
		}
    }
}