/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.AuthSecurityRole")]
    public class AuthSecurityRole extends AuthSecurityRoleBase {
		public static const ROLE_ADMIN:String = "ROLE_ADMIN";
		public static const ROLE_AUDITOR:String = "ROLE_AUDITOR";
		public static const ROLE_CLASSIFIER:String = "ROLE_CLASSIFIER";
		public static const ROLE_SUPER_ADMIN:String = "ROLE_SUPER_ADMIN";
		public static const ROLE_NONE:String = "ROLE_NONE";
    }
}