/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.AuthUser")]
    public class AuthUser extends AuthUserBase {
		public function hasRole(roleName:String): Boolean
		{
			if (roles == null) return false;
			
			for each (var i:* in roles)	
				if ((i as AuthSecurityRole).roleName == roleName)
					return true;
			
			return false;
		}
    }
}