/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.Config")]
    public class Config extends ConfigBase {
		
		override public function get nameKey():String
		{
			return "config." + this.key;
		}
		override public function set nameKey(value:String):void {
		}
    }
}