/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.DashboardItem")]
    public class DashboardItem extends DashboardItemBase {
		
		public static const RSS_MYDLP_BLOG:String = "blogrss";
		public static const RSS_DATALOSSDB:String = "datalossdbrss";
		
		public static const INCIDENTS_BY_PROTOCOLS_1H:String = "incident_by_protocols__1h";
		public static const INCIDENTS_BY_PROTOCOLS_24H:String = "incident_by_protocols__24h";
		public static const TOP_5_ADDRESS_1H:String = "top_5_address__1h";
		public static const TOP_5_ADDRESS_24H:String = "top_5_address__24h";
		public static const TOP_5_USERS_1H:String = "top_5_users__1h";
		public static const TOP_5_USERS_24H:String = "top_5_users__24h";
		public static const TOP_5_FILE_TYPE_1H:String = "top_5_file_type__1h";
		public static const TOP_5_FILE_TYPE_24H:String = "top_5_file_type__24h";
		public static const TOP_5_RULES_1H:String = "top_5_rules__1h";
		public static const TOP_5_RULES_24H:String = "top_5_rules__24h";
		public static const TOP_5_ITYPES_1H:String = "top_5_itypes__1h";
		public static const TOP_5_ITYPES_24H:String = "top_5_itypes__24h";
		public static const INCIDENT_BY_ACTIONS_1H:String = "incident_by_actions__1h";
		public static const INCIDENT_BY_ACTIONS_24H:String = "incident_by_actions__24h";
		public static const TOP_5_FILES_1H:String = "top_5_files__1h";
		public static const TOP_5_FILES_24H:String = "top_5_files__24h";
		public static const INCIDENTS_BY_PROTOCOLS_1W:String = "incident_by_protocols__1w";
		public static const INCIDENTS_BY_ACTIONS_1W:String = "incident_by_actions__1w";
		public static const TOP_5_ADDRESS_1W:String = "top_5_address__1w";
		public static const TOP_5_USERS_1W:String = "top_5_users__1w";
		public static const TOP_5_RULES_1W:String = "top_5_rules__1w";
		public static const TOP_5_ITYPES_1W:String = "top_5_itypes__1w";
	}
}