/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {
    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.EndpointStatus")]
    public class EndpointStatus extends EndpointStatusBase {
		public function get agent():String 
		{
			var ret:String = ""
			if (this.version != null && this.version.length > 0) 
			{
				ret += version;
			}
			
			if (ret != "")
			{
				ret += " ";
			}
			
			if (this.osName != null && this.osName.length > 1)
			{
				var firstChar:String = this.osName.substr(0, 1);
				var restOfString:String = this.osName.substr(1, osName.length);
				ret += "(" + firstChar.toUpperCase()+restOfString.toLowerCase() + ")";
			}
			return ret;
		}
    }
}