/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {
	import flashx.textLayout.elements.SpecialCharacterElement;
	
	import mx.resources.ResourceManager;

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.InformationFeature")]
	[ResourceBundle("messages")]
    public class InformationFeature extends InformationFeatureBase {
		
		public function get label():String
		{	
			if (this.matcher == null || this.matcher.functionName == null )
				return "";
			
			var retVal:String = ""; 
			
			var generatedNameKey:String = new String("matchers.");
			
			generatedNameKey += this.matcher.functionName + ".label";
			
			var resourceVal:String = ResourceManager.getInstance().getString("messages", generatedNameKey);
			if (resourceVal == null || resourceVal.length == 0)
				return "Custom" + " - " + this.threshold.toString();
			
			retVal += resourceVal;
			
			if(this.matcher.functionName == "keyword")
			{
				retVal += " - " + removeEscapeCharacter(this.matcher.matcherArguments.getItemAt(0).coupledArgument.regex);
			}
			else if(this.matcher.functionName == "keyword_group" ||
					this.matcher.functionName == "document_hash" || 
					this.matcher.functionName == "document_pdm" )
			{
				retVal += " - " + this.matcher.matcherArguments.getItemAt(0).coupledArgument.argument.label;
			}
			
			retVal += " - " + this.threshold.toString();
			return retVal;
		}
		
		public static function removeEscapeCharacter(string:String):String
		{
			var resultString:String = new String;
			for(var i:int = 0; i < string.length; i++)
			{
				if(string.charAt(i) == '\\' && string.charAt(i+1) == '\\')
				{
					resultString = resultString.concat(string.charAt(i));
					i++;
				}
				else if(string.charAt(i) != '\\')
					resultString = resultString.concat(string.charAt(i));
			}
			return resultString;
		}
    }
}