/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {
	import mx.resources.ResourceManager;

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.InformationFeature")]
	[ResourceBundle("messages")]
    public class InformationFeature extends InformationFeatureBase {
		
		public function get label():String
		{	
			var generatedNameKey:String = new String("matchers.");
			
			generatedNameKey += this.matcher.functionName + ".label";
			
			var resourceVal:String = ResourceManager.getInstance().getString("messages", generatedNameKey);
			if (resourceVal == null || resourceVal.length == 0)
				return "Custom" + " - " + this.weight.toString();
			else if(this.matcher.functionName == "keyword")
				return resourceVal + " - " + this.matcher.matcherArguments.getItemAt(0).coupledArgument.regex + " - " + this.weight.toString();
			else 
				return resourceVal + " - " + this.weight.toString();
			
		}
    }
}