/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {
	import mx.collections.ArrayCollection;
	import mx.collections.ListCollectionView;
	import mx.collections.Sort;
	import mx.collections.SortField;
	import mx.states.OverrideBase;

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.InventoryCategory")]
    public class InventoryCategory extends InventoryCategoryBase {
		
		protected var _isChildrenSorted:Boolean = false;
		
		public var sortPriority:Number = 3;
		
		override public function get children():ListCollectionView
		{
			if (_isChildrenSorted == false && super.children != null)
			{
				var sortLabel:Sort = new Sort();
				sortLabel.fields=[new SortField("sortPriority"), new SortField("label")];
				super.children.sort = sortLabel;
				super.children.refresh();
				_isChildrenSorted = true;
			}
			return super.children;
		}
		
		override public function set children(value:ListCollectionView):void
		{
			_isChildrenSorted = false;
			super.children = value;
		}
		
		override public function set editable(value:Boolean):void
		{
			if (editable)
			{
				sortPriority = 3;
			}
			else
			{
				sortPriority = 1;
			}
			super.editable = value;
		}
			
		override public function get editable():Boolean
		{
			return super.editable;
		}
    }
}