/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {
	import mx.collections.ArrayCollection;
	import mx.collections.ListCollectionView;

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.RDBMSConnection")]
    public class RDBMSConnection extends RDBMSConnectionBase {
		public static const DB_TYPE_MYSQL:String = "mysql";
		public static const DB_TYPE_POSTGRESQL:String ="postgresql";
		public static const DB_TYPE_ORACLE:String ="oracle";
		public static const DB_TYPE_DB2:String ="db2";
		public static const DB_TYPE_DB2_AS400:String ="db2-as400";
		
		public static const DB_TYPES:ListCollectionView = 
			new ArrayCollection(new Array(
				DB_TYPE_MYSQL
				/*
				DB_TYPE_MYSQL,
				DB_TYPE_POSTGRESQL,
				DB_TYPE_ORACLE,
				DB_TYPE_DB2,
				DB_TYPE_DB2_AS400
				*/
			));
		
    }
}