/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.Rule")]
    public class Rule extends RuleBase {
		public static const ACTION_PASS:String = "PASS";
		public static const ACTION_BLOCK:String = "BLOCK";
		public static const ACTION_LOG:String = "LOG";
		public static const ACTION_QUARANTINE:String = "QUARANTINE";
		public static const ACTION_ARCHIVE:String = "ARCHIVE";
		public static const ACTION_ENCRYPT:String = "ENCRYPT";
		public static const ACTION_CUSTOM:String = "CUSTOM";
    }
}