/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.mydlp.ui.domain {

    [Managed]
    [RemoteClass(alias="com.mydlp.ui.domain.WebServer")]
    public class WebServer extends WebServerBase {
		public static const PROTO_HTTP:String = "http";
		public static const PROTO_HTTPS:String = "https";
    }
}